/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/administrations/settings/': RouteRecordInfo<'/administrations/settings/', '/administrations/settings', Record<never, never>, Record<never, never>>,
    '/administrations/user/': RouteRecordInfo<'/administrations/user/', '/administrations/user', Record<never, never>, Record<never, never>>,
    '/administrations/user/UserForm': RouteRecordInfo<'/administrations/user/UserForm', '/administrations/user/UserForm', Record<never, never>, Record<never, never>>,
    '/administrations/user/UserShow': RouteRecordInfo<'/administrations/user/UserShow', '/administrations/user/UserShow', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/administrations/settings/index.vue': {
      routes: '/administrations/settings/'
      views: never
    }
    'src/pages/administrations/user/index.vue': {
      routes: '/administrations/user/'
      views: never
    }
    'src/pages/administrations/user/UserForm.vue': {
      routes: '/administrations/user/UserForm'
      views: never
    }
    'src/pages/administrations/user/UserShow.vue': {
      routes: '/administrations/user/UserShow'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
